### ISSUE TITLE
congratulations and Questions

### ISSUE THREAD

**Issue by xinli2008** [chandan047/GCN-GLAC#1]
hello,Your work on visual storytelling is excellent.I am trying to reproduce the result of the paper, but I have a problem in the preprocessing 1.download the dataset.
here is the detail of the question:
can i use the path to put the images :
./GCN-GLAC-master/train
./GCN-GLAC-master/test
./GCN-GLAC-master/val
or it mat be other path?
I am so sorry to bother you,I am so puzzled,i would appreciate it if you solve my question ,THANK you!

**Comment by chandan047** [comment]
It's from so long ago, I don't remember such a detail!
